### PR TITLE
Fix MFA scratch codes and QR code not working

### LINKED ISSUE #3909: Enabling MFA returns encrypted MFA scratch codes
**Describe the bug**
When enabling the MFA the scratch codes are returned encrypted, so they can't be used.

**To Reproduce**

1. Login to the system
2. Enable MFA
3. See the scratch codes

**Expected behavior**
The scratch codes should be given unencrypted.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by MDeLuise**
This PR fix the issue that prevent the scratch codes and QR code to work.
Now the scratch codes are displayed as plain text.

**Related Issue**
This PR fixes #3909.

### CODE REVIEW

File: service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/credential/mfa/shiro/MfaOptionServiceImpl.java [hunk 1]
```diff
@@ -212,7 +208,8 @@ public ScratchCodeListResult createAllScratchCodes(TxContext tx, ScratchCodeCrea
             // Create code
             ScratchCodeImpl codeImpl = new ScratchCodeImpl(scratchCodeCreator.getScopeId(), scratchCodeCreator.getMfaOptionId(), encryptedCode);
 
-            ScratchCode scratchCode = scratchCodeRepository.create(tx, codeImpl);
+            ScratchCode scratchCode = txManager.execute(tx -> scratchCodeRepository.create(tx, codeImpl));
+            scratchCode.setCode(code);
```
Comment (Coduz) [inline service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/credential/mfa/shiro/MfaOptionServiceImpl.java:214]: Please add a comment inline on why we are doing this `setCode` after the creation so next person here will figure that out right away :D

**Review by Coduz — CHANGES_REQUESTED** [review]
Just a small comment on the `setCode`

File: service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/credential/mfa/shiro/MfaOptionServiceImpl.java (hunk 1 above)
Comment (MDeLuise) [reply service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/credential/mfa/shiro/MfaOptionServiceImpl.java:214]: Thanks for the feedback, just updated the changes 😁

**Review by Coduz — APPROVED** [review]
