### PR TITLE
Fix Device and Device Event CSV Export

### LINKED ISSUE #3098: CSV file with exported device events is wrong
**Describe the bug**
The CSV with exported device events is wrong

1. The field `Account Name` shows the _client ID_
2. The field `Position Status` shows the _event type_ (MISSING, BIRTH, etc.)
3. The field `Response Code` shows the _event message_

Additionally, sometimes the CSV files contains no entries at all, just the column headers

**To Reproduce**
1. In _Device Filter_ filter by _Client ID_. 
1. Select the device and click on the _Events_ tab. 
1. Export the events clicking on _Export to CSV_. 

**Expected behavior**
A CSV file without the aforementioned issues

**Screenshots**
None

**Version of Kapua**
[e.g. 1.2.4]

**Type of deployment**
[x] Local Vagrant deployment
[x] Docker
[x] Openshift (in its variants) 
[x] Others

**Main component affected**
[x] Console (All browsers)
[ ] REST API
[ ] Message Broker
[ ] - Others

### PR DESCRIPTION
**Pull request by lorthirk**
Fixes for the Device and Device Event CSV Export

**Related Issue**
Fixes #3098

### CODE REVIEW

**Review by Coduz — APPROVED** [review]

File: console/module/account/src/main/java/org/eclipse/kapua/app/console/module/account/server/GwtAccountServiceImpl.java [hunk 1]
```diff
@@ -694,6 +694,7 @@ public UserListResult call() throws Exception {
                     }
                 });
 
+
```
Comment (Coduz) [inline console/module/account/src/main/java/org/eclipse/kapua/app/console/module/account/server/GwtAccountServiceImpl.java]: This breaks checkstyle 😁
