### PR TITLE
Fixed missing OpenID Provider session invalidation

### LINKED ISSUE #2971: SSO provider session not invalidated at Kapua session invalidation
**Describe the bug**
When the session expires, the user is logged out from the Kapua console. However, if the user is an external one logged through SSO, he can login again by simply clicking on the 'SSO Login' button, without the need to insert again his credentials. This is due to the SSO session not yet invalidated, while the Kapua Console one already is.

One possible solution would be to simply reduce the time of the SSO session to a lower value than the Kapua Console one. Note that the Kapua Console session time is set though the `session-timeout` tag in the `web.xml` in `console/web/src/main/webapp/WEB-INF`. However, this is not the best option, since there is no synchronisation between the two session. Also, it requires to configure the SSO Provider session timeout at each installation. A better option would be to invalidate the SSO session using the SSO OpenId Connect logout endpoint when the Kapua one is invalidated.

**To Reproduce**
1. Login to Kapua with an external SSO user (an SSO provider is required)
2. Wait 30 minutes (the Kapua session timeout), after this amount of time the user should be logged out
3. Click on the 'SSO Login' button
4. The user is logged in without the need to insert credentials.

**Expected behavior**
The SSO session should be invalidated at the same time as the Kapua one.

**Screenshots**
_N/A_

**Version of Kapua**
1.2.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

**Additional context**
_N/A_

### PR DESCRIPTION
**Pull request by gbarbon**
Logout from the OpenID Connect Provider in case the Kapua Console session is expired.

**Related Issue**
This PR fixes #2971 

**Description of the solution adopted**
Added an HttpSessionListener that listens to the Kapua Console session invalidation. When the session is invalidated, it performs an HTTP request to the OpenID Provider logout endpoint.

Note that this does not follow the same flow as the normal OpenID logout. Moreover, this feature can be disabled with a dedicated property called `console.sso.openid.session_listener.logout.enabled`.

**Screenshots**
_N/A_

**Any side note on the changes made**
Also updated comments and removed unused variables that are part of the SSO code.

This PR requires PR #2996 to be merged!

### CODE REVIEW

File: service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/CredentialsFactoryImpl.java [hunk 1]
```diff
@@ -39,8 +39,8 @@ public ApiKeyCredentials newApiKeyCredentials(String apiKey) {
     }
 
     @Override
-    public JwtCredentials newJwtCredentials(String jwt) {
-        return new JwtCredentialsImpl(jwt);
+    public JwtCredentials newJwtCredentials(String jwt, String idToken) {
```
Comment (LeoNerdoG) [inline service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/CredentialsFactoryImpl.java:42]: Hey @gbarbon,
can you change the header of this file to " * Copyright (c) 2011, 2020 Eurotech and/or its affiliates and others" ? 
Because last change is from the current year 😄

File: service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/JwtCredentialsImpl.java [hunk 2]
```diff
@@ -19,9 +19,11 @@
     private static final long serialVersionUID = -5920944517814926028L;
 
     private String jwt;
+    private String idToken;
```
Comment (LeoNerdoG) [inline service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/JwtCredentialsImpl.java:22]: Hey @gbarbon,
can you change the header of this file to " * Copyright (c) 2011, 2020 Eurotech and/or its affiliates and others" ? 
Because last change is from the current year 😄

**Review by LeoNerdoG — COMMENTED** [review]
Hey @gbarbon sorry to bother you again - there are some more headers to fix 😄

File: service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/CredentialsFactoryImpl.java (hunk 1 above)
Comment (gbarbon) [reply service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/CredentialsFactoryImpl.java:42]: Sure, done!

File: service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/JwtCredentialsImpl.java (hunk 2 above)
Comment (gbarbon) [reply service/security/shiro/src/main/java/org/eclipse/kapua/service/authentication/shiro/JwtCredentialsImpl.java:22]: Sure, done!
