### PR TITLE
Fix MetricPredicate and add MetricExistsPredicate

### LINKED ISSUE #2852: MetricPredicate translates to incompatible query in Elasticsearch REST Client
**Describe the bug**
The current implementation of `MetricPredicate` translate to a query that consider the Datastore Schema. Specifically, an example `MetricPredicate` would translate to JSON as

```
{
    "query": {
        "range" : {
            "temperature" : {
                "gte" : 10,
                "lte" : 20,
            }
        }
    }
}
```

While it should translate to this JSON to support our current schema:

```
{
    "query": {
        "range" : {
            "metrics.temperature.int" : {
                "gte" : 10,
                "lte" : 20,
            }
        }
    }
}
```

This means that filtering for a metric type and/or value would always return 0 entries

**To Reproduce**
1. Perform a REST call to `/{scopeId}/dataMessages` filtering on `metricName`, `metricType`, `metricMin` and `metricMax`

**Expected behavior**
A set of results matching the name, type and values would return

**Version of Kapua**
1.0.9
1.1.2

**Type of deployment**
[x] Local Vagrant deployment
[x] Docker
[x] Openshift (in its variants) 
[x] Others

**Main component affected**
[ ] Console (in case of console please report info on which browser you encountered the problem)
[x] REST API
[ ] Message Broker
[x] - Others

**Additional context**
Basically any component that uses di ES REST client is affected

### PR DESCRIPTION
**Pull request by lorthirk**
This PR fixes the current implementation of `MetricPredicate` and adds a new `MetricExistsPredicate` to cope with our Elasticsearch data schema

**Related Issue**
Fixes #2852 

**Description of the solution adopted**
`MetricPredicateImpl` has been reworked to match the "metrics.metricName.typ" notation; also `MetricExistsPredicate` has been created to match the schema notation. The current `ExistsPredicate` hasn't changed since it could be used for other fields

### CODE REVIEW

File: service/datastore/api/src/main/java/org/eclipse/kapua/service/datastore/model/query/MetricExistsPredicate.java [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+ * @since 1.0.0
+ */
+public interface MetricExistsPredicate extends ExistsPredicate {
+
+    /**
+     * Gets the metric type to search.
+     * This is required because metric with the same name can have different types.
+     *
+     * @return The metric type
+     * @since 1.0.0
```
Comment (Coduz) [inline service/datastore/api/src/main/java/org/eclipse/kapua/service/datastore/model/query/MetricExistsPredicate.java]: `@since 1.2.0`

File: service/datastore/api/src/main/java/org/eclipse/kapua/service/datastore/model/query/MetricExistsPredicate.java [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+ *
+ * Contributors:
+ *     Eurotech - initial API and implementation
+ *******************************************************************************/
+package org.eclipse.kapua.service.datastore.model.query;
+
+/**
+ * Query predicate for matching messages with existing metrics
+ *
+ * @since 1.0.0
```
Comment (Coduz) [inline service/datastore/api/src/main/java/org/eclipse/kapua/service/datastore/model/query/MetricExistsPredicate.java]: `@since 1.2.0`

File: service/datastore/api/src/main/java/org/eclipse/kapua/service/datastore/model/query/MetricExistsPredicate.java [hunk 3]
```diff
@@ -0,0 +1,38 @@
...
+     * @return The metric type
+     * @since 1.0.0
+     */
+    Class<?> getType();
+
+    /**
+     * Sets the metric type so search.
+     *
+     * @param type The metric type to search.
+     * @since 1.0.0
```
Comment (Coduz) [inline service/datastore/api/src/main/java/org/eclipse/kapua/service/datastore/model/query/MetricExistsPredicate.java]: `@since 1.2.0`

File: service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/model/query/MetricExistsPredicateImpl.java [hunk 4]
```diff
@@ -0,0 +1,71 @@
...
+import org.eclipse.kapua.service.datastore.internal.schema.KeyValueEntry;
+import org.eclipse.kapua.service.datastore.internal.schema.SchemaUtil;
+import org.eclipse.kapua.service.datastore.model.query.MetricExistsPredicate;
+
+import com.fasterxml.jackson.databind.node.ObjectNode;
+
+/**
+ * Implementation of query predicate for checking if a field exists
+ *
+ * @since 1.0
```
Comment (Coduz) [inline service/datastore/internal/src/main/java/org/eclipse/kapua/service/datastore/internal/model/query/MetricExistsPredicateImpl.java]: `@since 1.2.0`

**Review by Coduz — CHANGES_REQUESTED** [review]

**Review by Coduz — APPROVED** [review]
