### PR TITLE
Fix URL regex marking as invalid legal URL

### LINKED ISSUE #3788: URL regex does not accept valid URL
**Describe the bug**
The existing URL regex does not accept some valid URL, marking them as invalid. https://github.com/eclipse/kapua/blob/2c701fe144152db2c09bc200e8287a4f20ba4ecb/console/module/api/src/main/java/org/eclipse/kapua/app/console/module/api/client/util/validator/TextFieldValidator.java#L73

For example `http://172.16.0.2:1234/static/com.eurotech.opcua.driver_1.1.1.dp` is affected by this problem.

### PR DESCRIPTION
**Pull request by MDeLuise**
**Brief description of the PR.**
Some valid URLs was considered illegal, for example the following: `http://172.16.0.2:1234/static/com.eurotech.opcua.driver_1.1.1.dp`.
This PR is to fix this issue.

**Related Issue**
This PR fixes #3788.

**Description of the solution adopted**
Change the regex in order to include more URLs.

**Any side note on the changes made**
Added also the validation check on the backend side, in order to avoid console parameter validation bypass.

### CODE REVIEW

File: console/module/api/src/main/java/org/eclipse/kapua/app/console/module/api/client/util/validator/TextFieldValidator.java [hunk 1]
```diff
@@ -70,7 +69,7 @@ public enum FieldType {
         ALPHANUMERIC("alphanumeric", "^[a-zA-Z0-9_]+$"),
         NUMERIC("numeric", "^[+0-9.]+$"),
         PACKAGE_VERSION("package_version", "^[a-zA-Z0-9.\\-\\_]*$"),
-        URL("url", "(http(s)?:\\/\\/.)?(www\\.)?[-a-zA-Z0-9@:%._\\+~#=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%_\\+.~#?&//=]*)");
+        URL("url", "^(https?:\\/\\/)?(www\\.)?[-a-zA-Z0-9@:%._\\+~#=//]{1,256}\\.[a-zA-Z0-9()//]{2,6}\\b(?:[-a-zA-Z0-9()@:%_\\+.~#?&\\/=]*)$");
```
Comment (Coduz) [inline console/module/api/src/main/java/org/eclipse/kapua/app/console/module/api/client/util/validator/TextFieldValidator.java:72]: Isn't this making use of `https ` mandatory?

Comment (MDeLuise) [reply console/module/api/src/main/java/org/eclipse/kapua/app/console/module/api/client/util/validator/TextFieldValidator.java:72]: It's ok to have a URL without the `https` with this regex, in fact the first part of it have the trailing `?` character (`^(https?:\\/\\/)?`).

Screenshot 2023-06-09 at 16 44 45

**Review by Coduz — APPROVED** [review]
